spring:
  main:
    banner-mode: off
  application:
    name: coupon-api
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/_9dev
    username: _9dev
    password: _9dev
  data:
    redis:
      host: localhost
      port: 6379
