metastore:
  extraEnv:
    QW_METASTORE_URI: "postgres://_9dev:_9dev@postgresql.default.svc.cluster.local:5432/_9dev"

searcher:
  replicaCount: 1

config:
  default_index_root_uri: s3://quickwit/indexes

  storage:
    s3:
      flavor: minio
      region: local
      endpoint: http://main-hl.default.svc.cluster.local:9000
      access_key_id: "_9dev_minio_access_key"
      secret_access_key: "_9dev_minio_secret_key"
