apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: quickwit-default-log
spec:
  datasource:
    name: quickwit-default-log
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit-control-plane.default.svc.cluster.local:7280/api/v1
    jsonData:
      index: kubernetes-logs
      logMessageField: message
  instanceSelector:
    matchLabels:
      dashboards: grafana

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: quickwit-access-log
spec:
  datasource:
    name: quickwit-access-log
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit-control-plane.default.svc.cluster.local:7280/api/v1
    jsonData:
      index: access-logs
      logMessageField: line
  instanceSelector:
    matchLabels:
      dashboards: grafana
