apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: oci://quay.io/strimzi-helm
  name: strimzi-kafka-operator
  version: 0.45.0
  releaseName: strimzi-operator
  includeCRDs: true

resources:
- main-cluster.yaml
