apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: main-pool
  labels:
    strimzi.io/cluster: main-cluster
spec:
  replicas: 1
  roles:
  - controller
  - broker
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      class: local-path
      size: 16Gi
      deleteClaim: false
      kraftMetadata: shared

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: main-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
      configuration:
        brokers:
        - broker: 0
          advertisedHost: main-cluster-main-pool-0.main-cluster-kafka-brokers.default.svc.cluster.local
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
