apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: https://provectus.github.io/kafka-ui-charts
  name: kafka-ui
  releaseName: kafka-ui
  version: 0.7.6
  includeCRDs: true
  valuesFile: ./values.yaml
