console:
  replicaCount: 0

tenants:
- name: main
  pools:
  - servers: 1
    size: 16Gi
    storageClassName: local-path
  secrets:
    enabled: true
    name: minio-main-secret
    accessKey: "_9dev_minio_access_key"
    secretKey: "_9dev_minio_secret_key"
