apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: https://helm.vector.dev
  name: vector
  version: 0.41.0
  releaseName: vector-agent
  includeCRDs: true
  valuesFile: agent/values.yaml

