apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: local-path
  capacity:
    storage: 32Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/data/postgresql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
spec:
  storageClassName: local-path
  volumeName: postgresql
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
