apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: "https://charts.jetstack.io"
  name: cert-manager
  version: 1.17.1
  releaseName: cert-manager
  namespace: cert-manager
  valuesInline:
    crds:
      enabled: true

resources:
- namespace.yaml
