apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- repo: https://operator.min.io
  name: minio-operator
  releaseName: operator
  version: 4.3.7
  includeCRDs: true
  valuesFile: ./values.yaml
