apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  labels:
    app: ksqldb
spec:
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - name: ksqldb
        image: ksqldb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        startupProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: ksqldb-env
