apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: ksqldb-env
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml

replicas:
- name: ksqldb
  count: 1

images:
- name: ksqldb
  newName: confluentinc/cp-ksqldb-server
  newTag: 7.9.0
