apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: _9dev
      admin_password: _9dev
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: grafana
            env:
            - name: GF_INSTALL_PLUGINS
              value: "https://github.com/quickwit-oss/quickwit-datasource/releases/download/v0.4.6/quickwit-quickwit-datasource-0.4.6.zip;quickwit-quickwit-datasource"