apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: oci://ghcr.io/grafana/helm-charts
  name: grafana-operator
  version: v5.17.0
  releaseName: grafana-operator

resources:
- datasource.yaml
- grafana.yaml
