role: "Agent"

customConfig:
  data_dir: /vector-data-dir

  sources:
    kubernetes_log_source:
      type: kubernetes_logs

  transforms:
    kubernetes_log_route:
      type: route
      inputs:
      - kubernetes_log_source
      route:
        gateway_access_log: >-
          .kubernetes.container_name == "gateway"
          && contains(string!(.message), "reactor.netty.http.server.AccessLog")

    gateway_access_log_remap:
      type: remap
      drop_on_abort: true
      drop_on_error: true
      inputs:
      - kubernetes_log_route.gateway_access_log
      source: |
        .message = parse_json!(.message)
        .log = parse_common_log!(.message.message, "%+")

  sinks:
    kubernetes_log_sink:
      type: kafka
      inputs:
      - kubernetes_log_source
      bootstrap_servers: main-cluster-main-pool-0.main-cluster-kafka-brokers.default.svc.cluster.local:9092
      topic: infra.kubernetes.vector.logs.v1
      encoding:
        codec: json

    gateway_access_log_sink:
      type: kafka
      inputs:
      - gateway_access_log_remap
      bootstrap_servers: main-cluster-main-pool-0.main-cluster-kafka-brokers.default.svc.cluster.local:9092
      topic: infra.kubernetes.vector.logs.gateway.access.v1
      encoding:
        codec: json
