spring:
  application:
    name: product-api
  jpa:
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  undertow:
    accessLog:
      enabled: true
      rotate: false
      dir: /dev
      prefix: stdout
      suffix: ""
      pattern: >-
        {
        "remote_ip":"%a",
        "remote_hostname": "%h",
        "remote_user": "%u",
        "request_time":"%t",
        "protocol":"%H",
        "status_code":"%s",
        "request_method":"%m",
        "request_uri":"%U",
        "request_query":"%q"
        }

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/_9dev
    username: _9dev
    password: _9dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
