apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: product-api-env
  envs:
  - .env

resources:
- deployment.yaml
- secret.yaml
- service.yaml

replicas:
- name: product-api
  count: 2

images:
- name: product-api
  newName: product-api
  newTag: 0.0.1
